#=========================================================================================#
#            Imagae Analysis Tool of Camera Bursts for Vibrations Testing                 #
#                     Accepts Uploads of PNGs from Burst_# Folders                        #
#                                                                                         #
#                             Written by: Paige K. Ramage                                 #
#                                       June 2026                                         #
#                                                                                         #
# This program can be used to automate the vibration and image blur quantification using  #
# The folders generated by the Burst_Automated_Camera.py file with naming convention      #
# Burst_# where # is the burst taken in a certain test. This program requires pip install #
# cv2 to run properly. It also uses numpy, os, and glob. If these are not already         #
# downloaded onto your device, you will need to install them. This script analyzes image  #
# stability by measuring the displacement between images captured in each burst. It       #
# searches through all Burst_* folders within the specified directory, loads each TIFF    #
# image, and selects a predefined region of interest (ROI) containing the target of       #
# interest. The first image in each burst serves as the reference, and every subsequent   #
# image is compared to it using OpenCV's phaseCorrelate() function, which estimates the   #
# horizontal (dx) and vertical (dy) image shifts with subpixel accuracy. These            #
# displacement values are stored for all frames, and the total displacement magnitude is  #
# calculated for each comparison. Finally, the script reports the mean, standard          #
# deviation, and maximum displacement for each burst, providing a quantitative measure of #
# image motion that can be used to evaluate vibration, mechanical stability, or beam      #
# drift during image acquisition.                                                         #
#=========================================================================================#
 
import os
import glob
import cv2
import numpy as np

base_dir = "images/testing code"

# ROI coordinates (adjust to your USAF target)
x, y, w, h = 450, 320, 250, 250

for burst in sorted(glob.glob(os.path.join(base_dir, "Burst_*"))):

    print(f"\nProcessing {os.path.basename(burst)}")

    files = []

    for ext in ("*.tif", "*.TIF", "*.tiff", "*.TIFF"):
        files.extend(glob.glob(os.path.join(burst, ext)))

    files = sorted(files)

    print(f"Found {len(files)} images")

    if len(files) < 2:
        print("Reached Continue")
        continue

    print("Reached -1")

    ref = cv2.imread(files[0], cv2.IMREAD_GRAYSCALE).astype(np.float32)
    ref_roi = ref[y:y+h, x:x+w]
    print("Reached 0")

    dx_list = []
    dy_list = []

    print("Reached 01")

    for f in files[1:]:
        print("Reached 02")

        img = cv2.imread(f, cv2.IMREAD_GRAYSCALE).astype(np.float32)
        roi = img[y:y+h, x:x+w]

        shift, response = cv2.phaseCorrelate(ref_roi, roi)

        dx_list.append(shift[0])
        dy_list.append(shift[1])

        print(
            os.path.basename(f),
            f"dx={shift[0]:7.3f}",
            f"dy={shift[1]:7.3f}",
            f"corr={response:.3f}"
        )

    dx = np.array(dx_list)
    dy = np.array(dy_list)

    mag = np.sqrt(dx**2 + dy**2)

    print("\nSummary")
    print(f"Mean displacement : {mag.mean():.3f} px")
    print(f"Std displacement  : {mag.std():.3f} px")
    print(f"Max displacement  : {mag.max():.3f} px")